[[ch9]]
== Alternatív blokkláncok, fizetőeszközök, alkalmazások

A digitális fizetőeszközök evolúciójában a Bitcoin nem tekinthető se kiinduló-, se végpontnak. A bitcoin létrejöttét közel húsz év kutatómunka előzte meg az elosztott rendszerek és fizetőeszközök világában. A bitcoinnal egy forradalmian új technológia jött létre: a munkabizonyítékon (Proof-of-Work) alapuló elosztott közmegegyezés. A bitcoinnak ez a központi jeletőségű vívmánya egy sereg egyéb újításnak is teret nyitott a fizetőeszközök, a pénzügyi szolgáltatások, a közgazdaság, az elosztott rendszerek, a választási rendszerek, a kormányzás, és a különféle szerződések terén.

Ebben a fejezetben azokkal az innovatív eljárásokkal (pl. alternatív láncok, fizetőeszközök, alkalmazások) foglalkozunk, amelyeknek a bitcoin, illetve a blokklánc 2009-ben történő bemutatása nyitott teret, illetve amelyek azóta, annak egyfajta hajtásaiként jöttek létre. 

A fejezetben megemlített alt-coinok legalább 50-szerese marad majd említés nélkül (kiváltva ezek fejlesztőinek és felhasználóinak haragját). Célunk nem az alt-coinok értékelése vagy minősítése, sőt még csak nem is „legjelentősebb” fejlesztések a valamilyen szubjektív értékítéleten alapuló kiemelése, hanem az, hogy szemléltessük az ökoszisztéma változatosságát és gazdagságát, kiemelve azon fejlesztéseket, amelyek valamilyen újdonságot, vagy jelentős eltérést hoztak az addigiakhoz képest. Az alt-coinok néhány igazán érdekes példája pénzügyi szemszögből tulajdonképpen abszolút bukásnak minősíthető. Sokszor mégis pont ettől válnak igazán érdekessé, tanulmányozásra méltóvá. Ugyanakkor hangsúlyozni kell, hogy az itt leírtak semmilyen minőségben sem tekinthetőek befektetői kisokosnak.

Szinte naponta jelennek meg új fejlesztések, így szinte biztos, hogy néhány fontos alt-coin kimarad a felsorolásunkból, és az sincs kizárva, hogy pont az, amelyik  megváltoztatja majd a történelmet. Az innovációk gyorsaságe teszi vibrálóvá és izgalmassá ezt a szférát, és egyben garantálja, hogy ez a fejezet már nyomtatásba kerülésekor idejétmúlt lesz.

=== Az alternatív fizetőeszközök és blokkláncok osztályozása

A bitcoin egy nyílt forráskódú projekt, amelynek kódja számos egyéb szoftver alapjául szolgált. A bitcoin forráskódjából származó szoftverek legtöbbször  az alternatív, decentralizált fizetőeszközök, vagy az úgynevezett _alt-coinok_. Ezek az alt-coinok általában a bitcoinnal megegyező építőelemeket használnak a különböző digitális fizetőeszközök megvalósítához.

Egy sereg protokollt a bitcoin blokkláncra építve, ennek segítségével valósítottak meg. Ezek a _meta-coinok_, _meta-chainek_, vagy _blokklánc alkalmazások_, melyek a blokkláncot egyfajta alkalmazási platformként használják, vagy a bitcoin protokollt további protokoll rétegekkel bővítik. Ilyen például a Colored Coins, a Mastercoin, és a Counterparty.

Az alábbiakban néhány jelentősebb alt-coint fogunk megvizsgálni, többek között a Litecoin-t, a Dogecoin-t, a Freicoin-t, a Primecoin-t, a Peercoin-t, a Darkcoin-t, és a Zerocoin-t. Felhozott példáinkat történelmi okokból, vagy egy-egy specifikus újítás miatt tartjuk jelentősnek,  semmiképp sem azért, mert ezek az általunk  „legjobbnak”, vagy legértékesebbnek vélt alt-coinok.

Az alt-coinokon kívül számos olyan alternatív blokklánc implementáció is van, amelyek nem igazán felelnek meg a „coin” kategóriának, így ezeket a fejlesztéseket _alt-chain_-eknek hívom a továbbiakban. Ezek az alt-chainek a közegyezés algoritmusával  és az osztott blokklánccal megvalósított platform révén támogatják a szerződéseket, a név regisztrációkat, és egyéb alkalmazásokat. Az alt-chaineknek ugyanazokat az építő elemeket használják, mint a bitcoin, és néha az is előfordul, hogy fizetőeszközként, vagy egyfajta fizetési rendszerként használják őket, de az elsődleges céljuk nem az, hogy fizetőeszközként funkcionáljanak. Az alt-chainek közül a Namecoin-t, az Ethereum-ot, és az NXT fogjuk részletesebben megvizsgálni.

A bitcoinban használt munkabizonyíték (Proof-of-Work) mechanizmuson kívül az alternatív érmék olyan kísérleti protokollokat is tartalmaznak, amelyek a Proof-of-Resource és a Proof-of-Publishing rendszereken alapulnak. Ezek példáiként a Maidsafe-re és a Twister-re  fogunk részletesebben kitérni.

Végül meg kell említeni azokat a bitcoin versenytársakat is, amelyek felkínálják ugyan a digitális fizetőeszköz, vagy digitális fizetési hálózat lehetőségét, de nem használnak semmilyen decentralizált főkönyvet vagy munkabizonyítékon (Proof-of-Work) alapuló közmegyezési mechanizmust. Ide tartozik például a Ripple, illetve társai. Ezek a nem-blokklánc alapú technológiák kívül esnek e könyv keretein, így jelen fejezetben sem foglalkozunk velük.

=== Meta-coin platformok

A meta-coinok és meta-chainek olyan szoftver rétegek, amelyek a bitcoinra lettek ráépítve, azaz esetükben vagy egyfajta „fizetőeszköz a fizetőeszközben” implementációról, vagy a bitcoin rendszerén belüli platformról/protokollról van szó. Ezek a funkcionális rétegek járulékos tulajdonságokkal és adottságokkal a bitcoin protokollt, mégpedig úgy, hogy a bitcoin tranzakciókba és címekbe egyéb kiegészítő adatokat kódolnak. Az első ilyen típusú meta-coin implementációk különféle „hack”-eket használtak a bitcoin blokklánc meta-adatokkal történő bővítésére, így például bitcoin címekbe kódoltak adatokat, vagy felhasználatlan tranzakciós mezőket (például tranzakció szekvencia mezőket) hasznosítottak a járulékos protokollal kapcsolatos meta-adatok kódolására. Mióta bevezetésre került az OP_RETURN műveleti kód, a meta-coinok közvetlenebb módon tudnak a blokkláncba  meta-adatokat kódolni, és a legtöbb meta-coin ennek használatára állt át.

==== Szinezett érmék (Colored Coins)

Az úgynevezett Színezett Érmék (Colored Coins) olyan meta-protokoll, amely a bitcoin egy kis mennyiségéhez rendel hozzá további információkat. Ezeknek a szinezett érméknek az a célja, hogy a megjelölt bitcoint egyéb értékkel is felruházzák. Például képzeljünk el egy 1 dolláros bankjegyet, amelyre rápecsételjük azt a feliratot, hogy „Ez az Hiper-Szuper Kft..-nek egy 1 egységnyi részvényesi elismervénye”. Ekképp az 1 dolláros bankjegy két funkciót is betölt: bankjegy és egyben részvényesi elismervény. Mivel elismervényi aspektusa értékesebb fizetőeszközi minőségénél, így valószínűsíthető, hogy nem vele fogunk cukorkát vásárolni. Fizetőeszközi minősége tehát már nem tűnik hasznosnak. A Szinezett Érmék hasonló elven működnek, azaz a bitcoin egy adott és parányi részét egy másik minőséggel is felruházzák. A terminusban a „color” (szín) kifejezés arra utal, hogy egy adott egységet egy speciális jelentéssel, attribútummal látunk el. Az attribútum jelzi a specifikus minőség jelenlétét az így megjelölt egységben. A „színmegjelölést”, mint attribútumot természetesen metafórikusan értjük, azaz a Colored Coinok nem tartalmaznak színeket.

A Colored Coinok kezelésére speciális „pénztárca” programok szolgálnak, amelyek lajstromba veszik és értelmezik azokat a meta-adatokat, amelyeket a „colored” bitcoinokhoz csatoltak. Egy ilyen a pénztárca használatával a felhasználó egy adott mennyiségű „színtelen” (attribútum nélküli) bitcoint egy speciális jelentésű cimke hozzáadásával szinezett érmévé konvertálhat. Ez a cimke jelenthet részvényesi elismervényt, kupont, ingatlan tulajdont, árucikket, beváltható pénzt, és még sok minden mást. Csak a szinezett érme felhasználóin múlik, hogy milyen specifikus minőséggel ruházzák fel az adott „színnel” (attribútummal) ellátott coinokat. Ahhoz, hogy egy sima érme szinezett érmévé váljon, arra van szükség, hogy a felhasználó meghatározza a hozzá társított meta-adatokat, például kibocsájtás típusát, osztható, vagy osztathatatlan voltát, szimbólumát, leírását és egyéb adatokat. Miután egy sima coin szinezett érmévé válik, értékesíthetővé, oszthatóvá, illetve egyesíthetővé válik, és akár jutalékok kifizetésére is alkalmas lesz. A szinezett érmék visszaállíthatóak sima coinokká is, úgy, hogy megfosztjuk őket speciális minőségüktől, és visszaállítjuk „sima” bitcoin névértéküket.

Mindennek szemléltetéseképpen létrehoztunk 20 „MasterBTC” attribútummal ellátott szinezett érmét, amelyek specifikus minősége: kupon a jelen könyv egy-egy ingyenes példányához. Ezt követően a MasterBTC jelzéssel ellátott összes egység (azaz, az evvel az attribútummal ellátott colored coinok) értékesíthetőek vagy továbbadhatóak minden olyan bitcoin felhasználónak, akik rendelkeznek a kezeléséhez szükséges pénztárca programmal. Egy adott felhasználó a megszerzett colored coint átutalhatja más felhasználónak, vagy a kibocsájtónál beválthatja a könyv egy ingyenes példányára. Az ismertetett példa az alábbi linken érhető el: https://cpr.sm/FoykwrH6UY

.A jelen könyv egy ingyenes példányához kupont biztosító colored coin meta-adatának profilja:
====
[source,json]
----
{
  "source_addresses": [
    "3NpZmvSPLmN2cVFw1pY7gxEAVPCVfnWfVD"
  ],
  "contract_url": "https://www.coinprism.info/asset/3NpZmvSPLmN2cVFw1pY7gxEAVPCVfnWfVD",
  "name_short": "MasterBTC",
  "name": "Free copy of \"Mastering Bitcoin\"",
  "issuer": "Andreas M. Antonopoulos",
  "description": "This token is redeemable for a free copy of the book \"Mastering Bitcoin\"",
  "description_mime": "text/x-markdown; charset=UTF-8",
  "type": "Other",
  "divisibility": 0,
  "link_to_website": false,
  "icon_url": null,
  "image_url": null,
  "version": "1.0"
}
----
====

==== Mastercoin

A Mastercoin egy olyan bitcoinra illesztett protokoll, amely a bitcoin rendszerét kiterjesztve, különféle alkalmazásokhoz biztosít platformot. A Mastercoin elsősorban nem fizetési eszköz, jóllehet a Mastercoin tranzakciókhoz az MST megjelölésű fizetőeszközt használja. A Mastercoint legjobban talán úgy lehetne meghatározni, mint támogatói platformot, fizetőeszközök, vagyontárgyak, decentralizált eszközök cseréjénél, vagy például szerződések felépítésénél, és persze még számos más dolognál is. A Mastercoin egy olyasféle alkalmazási protokoll, amely a bitcoin pénzügyi tranzakciós transzport-rétegéhez van hozzáillesztve, hasonlóképpen a TCP-n futó HTTP-hez.

A Mastercoin elsősorban azon tranzakciókon keresztül operál, amelyek egy speciális bitcoin címről, vagy címre érkeznek (ezt „exodus” címnek hívjuk, +1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P+), hasonlóképpen ahhoz, ahogy a HTTP is egy speciális portot (80 port) használ arra, hogy megkülönböztesse szállított forgalmát a TCP egyéb forgalmától. A Mastercoin protokoll a tranzakciók meta-adatait a speciális exodus címmel és többszörös aláírások használatával kódolja. A Mastercoin a jövőben fokozatosan az OP_RETURN bitcoin operátor használatára tér át.

==== Counterparty

A Counterparty szintén egy bitcoinra illesztett protokoll, amely fizetőeszközök, átruházható zsetonok, pénzügyi eszközök, és decentralizált vagyontárgyak cseréinek, illetve egyéb speciális alkalmazásoknak a gyűjtőtára. A Counterparty implementációja elsősorban a bitcoin script nyelv OP_RETURN operátorát használja a meta-adatok rögzítésére, melyek  járulékos jelentéssel bővítik ki a bitcoin tranzakciókat. A Counterparty az XCP jelzést használja a Counterparty tranzakciók során.

=== Alt-coin-ok

Az alt-coin-ok olyan digitális fizetőeszközök, melyek  implementációi  a bitcoinnal azonos tervezési mintát követnek, de teljesen különálló blokklánccal és hálózattal rendelkeznek. Az alt-coinok túlnyomó része a bitcoin forráskódjából eredeztethető, így ezeket „elágazások” („forks”) néven is szokás említeni. Néhányan közülük a „semmiből” lettek implementálva, azaz a blokklánc modellre támaszkodnak, de anélkül, hogy bármit is felhasználnának a bitcoin forráskódjából. Az alt-coinok és az alt-chainek (melyekre a következő részben térünk ki részletesebben) a blokklánc technológia teljesen különálló implementációi, tehát mindegyik változat a saját blokkláncát használja. A terminusok (alt-coin, alt-chain) közötti különbség arra utal, hogy míg az alt-coinok elsősorban fizetőeszközként funkcionálnak, addig az alt-chain-ek általában más céllal kerülnek alkalmazásra.

Az első alt-coinok 2011 augusztusában jelentek meg, mint a bitcoin forráskód „elágazásai”. Szigorúan véve, a bitcoin kód első jelentős alt-coinja igazából nem is alt-coin volt, hanem egy _Namecoin_ nevű alt-chain, de erről a következő részben írunk részletesebben.

A bejelentés időpontja alapján első alt-coinnak az _IXCoin_ minősíthető, amelyet 2011 augusztusában indítottak útjára. Az IXCoin-ban csak  néhány bitcoin paramétert változtattak meg, például felgyorsították  a fizetőeszköz „előállítását”, 96 érmére növelve a blokkokért járó jutalmat.

2011 szeptemberében indult útjára a _Tenebrix_. A Tenebrix volt az első olyan kriptopénz, amely egy alternatív munkabizonyíték (Proof-of-Work) rendszeren alapuló algoritmust, az úgynevezett _scrypt_-et implementálta. A scrypt algoritmus eredetileg jelszavak megerősítésére szolgált (hogy ellenáljanak a nyers erővel (brute-force) történő töréseknek). A hivatalos közlemény szerint a Tenebrix kifejlesztésénél az volt a vezérelv, hogy egy olyan coint hozzanak létre, amely ellenálló mind a GPU, mind az ASIC tipusú bányászattal szemben, mert  memória-igényes algoritmust használ. A Tenebrix, mint fizetőeszköz ugyan nem könyvelt el különösebb sikereket, de megalapozta a Litecoin-t, amely óriási népszerűségre tett szert, egyben klónok százai előtt nyitotta meg az utat.

A _Litecoin_ azon kívül, hogy a scrypt-et használja munkabizonyíték (Proof-of-Work) algoritmusnak, egy gyorsabb blokk-generálási időt is implementál, 2,5 percre csökkentve a bitcoin 10 perces intervallumát. A Litecoin-t úgy is szokták emlegetni, hogy ez az „ezüst, ha a a bitcoin az arany”, és nem vitás, hogy alternatív fizetőeszközként a bitcoin egy könnyűsúlyú versenytársa. A gyorsabb megerősítési időnek, illetve a maximum 84 millió érme összmennyiségnek köszönhetően, számos Litecoin hívő gondolja úgy, hogy az „ezüst érme” a kereskedelmi tranzakciók területén a bitcoinnál jobb megoldást jelent. 

A bitcoinra vagy Litecoin-ra támaszkodó különféle alt-coin sarjak száma 2011 és 2012 folyamán tovább nőtt, és 2013 elején már közel 20 alt-coin versenyzett piaci pozíciószerzésért. 2013 végére a különféle alt-coinok száma megtízszereződött, elérve a 200-as határt, így vitathatatlan, 2013 az „alt-coinok éve volt.” Természetesen a növekedés folytatódott, 2014-ben már közel 500 alt-coin létezéséről tudunk. Napjainkban az alt-coinok több mint a fele Litecoin klón.

Létrehozni egy alt-coint viszonylag egyszerű feladat, ezért is van már belőle több mint 500. Legtöbbjük csak nagyon kis eltérést mutat a bitcoinhoz képest, és igazából semmi említésre méltót sem tartalmaz. Sok közülük csak arra a célra szolgál, hogy a fejlesztőjét gazdagabbá tegye. A „pump-and-dump” sémák (manipulatív módon felvinni az altcoin árát, majd hirtelen elárasztani vele a piacot) és az utánzók között azért természetesen van néhány figyelemre méltó kivétel, és igazán fontos innováció is. Ezek az alt-coinok vagy egy egészen eltérő megközelítést alkalmaznak, vagy a bitcoin tervezési mintáját jelentős újítással bővítik. Alapvetően három olyan területet tudunk elkülöníteni, amelyekben az említett alt-coinok változást hoztak a bitcoinhoz képest:

* Eltérő pénzügyi irányelvek
* Eltérő munkabizonyíték (Proof-of-Work) rendszer, vagy eltérő konszenzus/közmegegyezési mechanizmus
* Különleges jellemzők, mint például a fokozottabb anonimitás

Az alt-coinok és alt-chain-ek grafikus idővonala az alábbi linken tekinthető meg: http://mapofcoins.com.

==== Egy alt-coin kiértékelése

Hogyan lehet eldönteni, hogy a rengeteg alt-coin közül melyek a valójában figyelemre méltó fejlesztések? Vannak alt-coinok, amelyek arra tesznek kísérletet, hogy széles körben, mint fizetőeszköz kerüljenek felhasználásra. Mások inkább laboratóriumi próbálkozások, melyek különböző jellegzetességekkel, vagy pénzügyi modellekkel kísérleteznek. Számos fejlesztés pedig kizárólag a fejlesztőik gyors meggazdagodásának a céljából született. Az alt-coinok kiértékeléséhez azok sajátos jellegzetességeit és piaci paramétereit vettem figyelembe.

Íme pár kérdés, amit érdemes feltenni egy alt-coinnal kapcsolatban, amikor azt bitcoinnal összevetve vizsgáljuk:

* Hozott e valamilyen jelentős innovációt az alt-coin?
* Kellőképpen különbözik-e az adott alt-coin a bitcointól? 
* Az adott eltérés elég vonzó-e ahhoz, hogy felkeltse a bitcoin felhasználók figyelmét? 
* Az adott alt-coin kapcsolódik-e egy érdekes piaci szektorhoz vagy alkalmazáshoz? 
* Képes-e elegendő bányász figyelmét felkelteni a támadásokkal szembeni biztonságos működéshez?

Néhány megvizsgálandó piaci és pénzügyi faktor:

* Mekkora az adott alt-coin teljes piaci kapitalizációja?
* Mennyi alt-coin becsült felhasználóinak/pénztárcáinak a száma?
* Mekkora az alt-coint elfogadó kereskedők száma?
* Mekkora az adott alt-coin végrehajtott tranzakcióinak a száma?
* Mekkora a napi tranzakciók értéke?

Könyvünk jelen fejezetében elsősorban az alt-coinok technikai jellegzetességeire és potenciális innovációira koncentrálunk, tehát az imént felsorolt kérdések első felére.

==== Pénzügyi paraméterű alternatívák: Litecoin, Dogecoin, Freicoin

A bitcoin néhány pénzügyi paramétere egy deflációs, fix kibocsátású pénz jellemzőivel ruházza fel a bitcoint.  Mennyisége 21 millió egységre (vagy 2100 billió kisebb egységre) korlátozódik, kibocsátásának sebessége szabályosan (mértani sorozat szerint) csökken, és „szívverésének” üteme - a tranzakciók visszaigazolásának és a blokkok legenerálásának az ideje - 10 perc. Számos alt-coin változtatta meg ezt a három paramétert, hogy így egy eltérő monetáris keretrendszert hozzon létre. A több száz ilyen típusú alt-coin közül a leginkább figyelemre méltó fejlesztések a következőek:

*Litecoin*

A Litecoin, amely az egyik legelső alt-coin 2011-ből, a bitcoin utáni a második legsikeresebb digitális fizetőeszköz. Elsődleges innovációi a scrypt, mint Proof-of-Work algoritmus alkalmazása (Tenebrix-től örökölt újítás), illetve a gyorsabb/könnyebb fizetőeszköz paraméterek.

* Blokk-legenerálási idő: 2,5 perc
* Maximális érme mennyiség: 84 millió egység, 2140-ig. 
* Az egyezményes algoritmus: scrypt Proof-of-Work
* Piaci kapitalizáció: 160 millió amerikai dollár 2014 első félévében.

*Dogecoin*

A Dogecoin 2013 decemberében indult útjára, mint a Litecoin egyik „elágazása”. A Dogecoin azért érdekes, mert monetáris politikája gyors kibocsátást ír elő, továbbá fizetőeszköz kapitalizációja kellőképpen magas ahhoz, hogy felhasználóit fizetésre, illetve költésre motiválja. Abból a szempontból is figyelemre méltó, hogy eredetileg csak viccnek szánták, azonban viszonylag gyorsan nagy népszerűségre tett szert, és egy relatív nagy és aktív felhasználói közösséggel is rendelkezett, 2014-es gyors hanyatlását megelőzően.

* Blokk-legenerálási idő: 60 másodperc
* Maximális érme mennyiség: 100,000,000,000 (100 milliárd) Doge, 2015-ig.
* Az egyezményes algoritmus: scrypt Proof-of-Work 
* Piaci kapitalizáció: 12 millió amerikai dollár 2014 első félévében.

*Freicoin*

A Freicoin 2012 júliusában kezdte meg pályafutását. Ez egy _inflálódó fizetőeszköz_, ami azt jelenti, hogy az érték tárolásához negatív kamatláb tartozik. A Freicoin-ban tárolt érték után évente 4,5 % díj kerül felszámításra, ami serkenti a fogyasztást, és visszatartja a pénz felhalmozását. A Freicoin azért érdekes, mert egy olyan monetáris politikát implementál, amely pontosan a bitcoin deflációs politikájának az ellentettje. A  Freicoin mint fizetőeszköz nem igazán lett sikeres, jelentősége inkább abban van, hogy jól szemlélteti az alt-coinok képviselte monetáris politikák változatosságát.

* Blokk-legenerálási idő: 10 perc
* Maximális érme mennyiség: 100 millió érme, 2140-ig. 
* Az egyezményes algoritmus: SHA256 Proof-of-Work
* Piaci kapitalizáció: 130 000 amerikai dollár 2014 első félévében

==== A konszenzusrendszer újításai: Peercoin, Myriad, Blackcoin, Vericoin, NXT

A bitcoin konszenzus mechanizmusa munkabizonyíték (Proof-of-Work) alapú, és az SHA256 algoritmust használja. Az első alt-coinok a scrypt-et használták alternatív Proof-of-Work algoritmusként, ekképp az egyébként ASIC centralizációra hajlamos bányászat, CPU-barát folyamattá vált. A scrypt alkalmazása után a konszenzus mechanizmus  lett az áttörő innovációk fő területe. Alt-coinok garmadáinál figyelhető meg a változatos algoritmus implementáció, például a scrypt, a scrypt-N, a Skein, a Groestl, a SHA3, a X11, a Blake, és stb. adoptációja. Néhány alt-coin egyszerre több algoritmust is alkalmaz a Proof-of-Work rendszerhez. 2013 folyamán a Proof-of-Work rendszernek egy olyan alternatívájával is találkoztunk, amelyet _kockázati bizonyítéknak_ (_Proof-of-Stake_) hívnak, és amely számos modern alt-coin alapját képzi.

A kockázati bizonyíták (Proof-of-Stake) egy olyan struktúra, amellyel a fizetőeszköz tulajdonosai leköthetik fizetőeszközüket, mint egyfajta kamatozó biztosítékot. A letéti bizonylathoz (Certificate of Deposit azaz CD) hasonlóan a résztvevők leköthetik megtakarításaik egy részét, ezáltal nyereségre tehetnek szert új fizetőeszközök formájában (kamatkifizetésként) és traznakciós díjak formájában.

*Peercoin*

A Peercoin-t 2012 augusztusában indították útjára, és ez volt az első olyan alt-coin, amely az új fizetőeszköz kibocsátásához a munkabizonyíték (Proof-of-Work) és a kockázati bizonyíték (Proof-of-Stake) algoritmusának a keverékét használta.

* Blokk-legenerálási idő: 10 perc
* Maximális érme mennyiség: nincs korlátozás. 
* Az egyezményes algoritmus: (Hibrid) Proof-of-Stake, kezdetben pedig Proof-of-Work rendszer  
* Piaci kapitalizáció: 14 millió amerikai dollár 2014 első félévében

*Myriad*

A Myriad 2014 februárjában jelent meg, és azért említésre méltó, mert, öt különböző Proof-of-Work algoritmust alkalmaz (SHA256d, Scrypt, Qubit, Skein vagy Myriad-Groestl) egyszerre, és a nehézség a bányászati részvétel függvényében minden algoritmusnál más-más lehet. A Myriad mögött meghúzódó szándék az, hogy az alt-coint éppúgy immúnissá tegye legyen az ASIC specializációval és központosítással szemben, mint az egyesített támadásokkal szemben, mivel a több bányász algoritmust egyidejűleg kellene támadni.

* Blokk-legenerálási idő: átlagosan 30 másodperc (2,5perces iránycél bányászalgoritmus típusonként)
* Maximális érme mennyiség: 2 milliárd, 2024-ig 
* Az egyezményes algoritmus: több algoritmust alkalmazó Proof-of-Work 
* Piaci kapitalizáció: 120 000 amerikai dollár 2014 első félévében

*Blackcoin*

A Blackcoin 2014 februárjában jelent meg, és a kockázati (Proof-of-Stake) algoritmust használ a közmegegyezésre. Azért érdemel figyelmet, mert bevezette a „multipools”-t, azaz a bányásztársulatoknak egy olyan típusát, amely automatikusan tud váltani a különböző alt-coinok között, attól függően, hogy melyiknél rentábilisabb a bányászat.

* Blokk-legenerálási idő: 1 perc
* Maximális érme mennyiség: nincs korlátozás 
* Az egyezményes algoritmus: Proof-of-Stake
* Piaci kapitalizáció: 3,7 millió amerikai dollár 2014 első félévében

*VeriCoin*

A VeriCoin 2014 májusában jelent meg. Kockázati (Proof-of-Stake) algoritmust használ a közmegegyezésre, de olyan váltakozó kamatlábbal, amely a piaci kínálat és kereslet szerint, dinamikusan alakul. Ugyancsak ez az első olyan alt-coin, amely automatikusan váltódik át bitcoinra, a pénztárcából történő bitcoinos fizetéseknél.

* Blokk-legenerálási idő: 1 perc
* Maximális érme mennyiség: nincs korlátozás 
* Az egyezményes algoritmus: Proof-of-Stake
* Piaci kapitalizáció: 1,1 millió amerikai dollár 2014 első félévében

*NXT*

A NXT (ejtsd: „Next”) egy „színtiszta” Proof-of-Stake alt-coin, legalábbis abban az értelemben, hogy nem alkalmazza a Proof-of-Work bányászatot. Az NXT egy a „semmiből” implementált kripto-fizetőeszköz, tehát sem nem a bitcoinnak, sem más alt-coinnak nem az elágazása. Az NXT számos továbbfejlesztett tulajdonsággal rendelkezik, pl. név regisztrációval (a Namecoinhoz hasonlóan), decentralizált eszközök cserelehetőségével (Colored Coin-okkal megegyezően), beépített decentralizált és biztonságos üzenetváltással (akárcsak a Bitmessage), és kockázat delegálással (a Proof-of-Stake-t másokra átruházva). A NXT hívei a „következő-generációs”, vagy 2.0 kriptopénznek is hívják ezt az alt-coint.

* Blokk-legenerálási idő: 1 perc
* Maximális érme mennyiség: nincs korlátozás 
* Az egyezményes algoritmus: Proof-of-Stake
* Piaci kapitalizáció: 30 millió amerikai dollár 2014 első félévében

==== Kettős-célú bányászati innovációk: Primecoin, Curecoin, Gridcoin

A bitcoin Proof-of-Work algoritmusának egy célja van: biztosítani a bitcoin hálozat biztonságát. A hagyományos kifizető rendszerek védelméhez hasonlítva a bányászat költségei nem is olyan jelentősek. Ennek ellenére sokak részéről érkezett olyan kritika, hogy a bányászat „költséges”. Az alt-coinok következő csoportja erre próbál megoldást találni. A kettős-célú Proof-of-Work algoritmus egyrészt egyes specifikus „hasznos” problémákat old meg, másrészt a hálózat védelmére is használja  a Proof-of-Work rendszert. Ha a fizetőeszköz védelmére szolgáló algoritmus egy külső felhasználással is rendelkezik, akkor ennek az a  a kockázata, , hogy az külső hatás is befolyásolja kereslet- kínálat görbéjét.     

*Primecoin*

A Primecoin 2013 júliusában látott napvilágot. Proof-of-Work algoritmusa prímszámok után kutat, nevezetesen Cunningham-  és ikerprím láncok után. A prímszámok a tudomány számos területén hasznosak. A Primecoin blokklánca a munkabizonyíték algoritmussal feltárt  prímszámokat tartalmazza, ekképp a tudományos felfedezéseknek egyfajta nyilvános tárhelye, emellett egyben a tranzakciók  nyilvános jegyzéke is.

* Blokk-legenerálási idő: 1 perc
* Maximális érme mennyiség: nincs korlátozás 
* Az egyezményes algoritmus: Proof-of-Work rendszer prímszám láncok feltárásával 
* Piaci kapitalizáció: 1,3 millió amerikai dollár 2014 első félévében

*Curecoin*

A Curecoin 2013 májusában jelent meg. Az SHA256 Proof-of-Work algoritmust kombinálja a fehérjék feltekeredésének a tanulmányozásával a „Folding@Home” projekten keresztül. A fehérjék feltekeredésésenk modellezése a fehérjék közötti biokémiai kölcsönhatások számításigényes szimulációját igényli, és a segítségével betegségek új gyógymódjai fedezhetők fel.

* Blokk-legenerálási idő: 10 perc
* Maximális érme mennyiség: nincs korlátozás 
* Az egyezményes algoritmus: Proof-of-Work rendszer fehérjék összehajtogatódásának/feltekeredésének a kutatásával 
* Piaci kapitalizáció: 58 000 amerikai dollár 2014 első félévében

*Gridcoin*

A Gridcoin-t 2013 októberében mutatták be. A scrypt-alapú Proof-of-Work rendszert a nyílt forrású BOINC rács-számításokban (grid computing) való részvételért cserébe adott jutalommal egészíti ki. A BOINC egy nyílt forráskódú protokoll, amelyeket tudományos kutatások rács-számításaiban használnak, és amely lehetővé teszi a résztvevők számára, hogy saját számítási kapacitásukat megosszák egy kiterjedtebb, akadémiai szintű kutatás számítási kapacitásával. A Gridcoin a BOINC-ot, mint általános számítási platformot használja, tehát nem olyan specifikus problémák megoldására, mint amilyen például a prímszámok keresése, vagy a fehérjék feltekeredésének a szimulációja.

* Blokk-legenerálási idő: 150 másodperc
* Maximális érme mennyiség: nincs korlátozás 
* Az egyezményes algoritmus: Proof-of-Work rendszer, BOINC grid computing, jutalommal kiegészítve
* Piaci kapitalizáció: 122 000 amerikai dollár 2014 első félévében

==== Anonimitás-fokuszú alt-coinok: CryptoNote, Bytecoin, Monero, Zerocash/Zerocoin, Darkcoin

A bitcoint, gyakran hibásan, anonim fizetőeszközként is jellemzik. Holott adat elemzéssel viszonylag egyszerűen felderíthető egy bitcoin cím mögött megbújó személyazonosság, és a bitcoin címek összekapcsolásával átfogó képet kaphatunk egy adott felhasználó bitcoin költekezési szokásairól. Számos olyan alt-coin született, amely kifejezetten ennek kérdésnek a megoldására szolgál, és amelyik kifejezetten a fokozott anonimitásra fókuszál. A legelső ilyen próbálkozás valószínűleg a _Zerocoin_ volt, amely a bitcoinra épülő,  és az anonimitást megőrző meta-coin protokol. A Zerocoint 2013-ban az IEEE Biztonsági és Titkosítási (Security and Privacy) szimpoziumán mutatták be. A Zerocoin egy teljesen külön alt-coinként, Zerocash néven kerül majd megvalósításra, evvel kapcsolatban jelenleg is folynak a fejlesztések. Szintén az anonimtásra fókuszáló alternatíva a 2013 októberében bemutatott _CryptoNote_. A CryptoNote egy olyan alapvető technológia, amelyet számos alt-coin elágazás használ, és amelyről részletesebben alább  lesz szó. A Zerocash-en és a Cryptonote-on kívül még egy sereg független és anonim alt-coint ismerünk, például a Darkcoin-t, amely lopakódó (stealth) titkos címekkel, vagy tranzakciók összekeverésével valósítja meg az aninimitást.

*Zerocoin/Zerocash*

A Zerocoin a digitális fizetőeszköz anonimitásának elméleti megközelítése, a fejlesztést 2013-ban mutatták be a Johns Hopkins Egyetem kutatói. A Zerocash a Zerocoinalt-coin megvalósítása, és jelenleg is folyik a fejlesztése.

*CryptoNote*

A CryptoNote egy olyan referencia alt-coin implementáció, amely egy 2013 októberében bemutatott digitális anonim pénz alapjait biztosítja. Úgy lett kifejlesztve, hogy változatos implementációkhoz szolgálhasson elágazásként, illetve rendelkezik egy beépített periodikus „reset” mechanizmussal is, amely meggátolja, hogy a CryptoNote, mint fizetőeszköz kerüljön felhasználásra. A CryptoNote-ból rengeteg alt-coin született. Ide tartozik például a Bytecoin (BCN), az Aeon (AEON), a Boolberry (BBR), a duckNote (DUCK), a Fantomcoin (FCN), a Monero (XMR), a MonetaVerde (MCN) és a Quazarcoin (QCN). A CryptoNote azért is figyelemre méltó, mert nem a bitcoin egy elágazása, hanem teljes egészében újszerű kriptopénz implementáció.

*Bytecoin*

A Bytecoin volt az első CryptoNote-on alapuló implementáció, azaz a CryptoNote technológiáján alapuló első életképes anonim fizetőeszköz. A Bytecoin 2012 júliusában jelent meg. Itt kell megemlítenünk, hogy volt egy korábbi Bytecoin nevű alt-coin is BTE rövidítéssel. A CryptoNote derivatíva fizetőeszközének így BCN a rövidítése. A Bytecoin a Cryptonight Proof-of-Work algoritmust használja, amely legalább 2 MB ramot igényel bányász példányonként, ezáltal elkalmatlan a GPU vagy az ASIC típusú bányászatra. A Bytecoin örökölte a CryptoNote-ból a ring-signatures-t, a belinkelhetetlen tranzakciókat és a blokklánc-elemzőkkel szembeni ellenállóképességégt az anonimitás megőrzése érdekében.

* Blokk-legenerálási idő: 2 perc
* Maximális érme mennyiség: 184 milliárd BCN 
* Az egyezményes algoritmus: Cryptonight Proof-of-Work 
* Piaci kapitalizáció: 3 millió amerikai dollár 2014 első félévében

*Monero*

A Monero is egy CryptoNote implementáció. A kibocsátási görbéje a Bytecoin-nál egy árnyalatnyival előnyösebb, mivel az érmék 80% az első négy év során kerül kibocsátásra. Anonimitásra vonatkozó tulajdonságait a CryptoNote-tól örökölte, így azzal megegyeznek.

* Blokk-legenerálási idő: 1 perc
* Maximális érme mennyiség: 18,4 millió XMR 
* Az egyezményes algoritmus: Cryptonight Proof-of-Work 
* Piaci kapitalizáció: 5 millió amerikai dollár 2014 első félévében

*Darkcoin*

A Darkcoin 2014 januárjában indult útjára, anonim fizetőeszközt  implementál úgy hogy, az összes úgynevezett DarkSend tranzakcióhoz újra-keverő (re-mixing) protokollt használ. A Darkcoin azért is érdekes, mert 11 különböző hash funkciót (blake, bmw, groestl, jh, keccak, skein, luffa, cubehash, shavite, simd, echo) használ a Proof-of-Work algoritmushoz.

* Blokk-legenerálási idő: 2,5 perc
* Maximális érme mennyiség: 22 millió DRK 
* Az egyezményes algoritmus: Multi-algoritmusos Multi-round Proof-of-Work 
* Piaci kapitalizáció: 19 millió amerikai dollár 2014 első félévében

=== Nem fizetőeszközként használt alt-chainek

Az alt-chainek a blokklánc programozási minta alternatív implementációi, és elsősorban nem fizetőeszközként kerülnek alkalmazásra. Számos közülük fizetőeszközt is tartalmaz, de ez a fizetőeszköz inkább, mint szimbólum/zseton kerül alkalmazásra, egyéb javak, vagy például egy szerződés szétosztásánál. Más szóval: a fizetőeszköz nem a platform lényegi kérdése, csak egy amolyan másodlagos adottsága.

==== Namecoin

A Namecoin volt a bitcoin kód első elágazása. A Namecoin egy olyan decentralizált kulcsnyilvántartási és transzfer platform, amely blokkláncot használ. Az Internet domain-név regisztrációs rendszeréhez hasonló, globális domain-név nyilvántartást támogat. A Namecoin-t jelenleg a +.bit+ gyökérdomain esetében alternatív Domain Név Szolgáltatóként (DNS) alkalmazzák. A Namecoin más névtérben lévő nevek és értékpárok nyilvántartására is alkalmas, például olyan dolgok tárolására, mint az email címek, a titkosítási kódok, az SSL tanusítványok, a file aláírások, a szavazói regiszterek, és még számtalan egyéb tanúsítvány és alkalmazás tárolására.

A Namecoin rendszere magában foglalja a namecoin fizetőeszközt is (szimbóluma NMC), amelyet a név-regisztrációk és név-cserék tranzakciós dijainak a megfizetésére használnak. Jelenleg egy névregisztráció díja 0,01 NMC, azaz körülbelül 1 cent. A bitcoinhoz hasonlóan, a díjakat a Namecoin bányászok kapják.

A Namecoin alap paraméterei megegyeznek a bitcoinéval:

* Blokk-legenerálási idő: 10 perc
* Maximális érme mennyiség: 21 millió NMC, 2140-ig. 
* Az egyezményes algoritmus: SHA256 Proof-of-Work
* Piaci kapitalizáció: 10 millió amerikai dollár 2014 első félévében

A Namecoin névtere nem korlátozott, bárki, bárhogyan és bármilyen névteret használhat. Mindamellett, néhány névtér rendelkezik egy jóváhagyott specifikációval, így amikor a blokkláncból kerül beolvasásra, a szoftver tudja, hogyan olvassa és hajtsa végre. Ha a név nem jólt formált, akkor a használt szoftvertől függetlenül hibát fogunk kapni. Íme, néhány példa a kedvelt névterekből:

* +d/+ a +.bit+ domain névtér domain-neve
* +id/+ a személyes adatok, mint például email cím, PGP kulcsok, stb. jegyzékének a névtere
* +u/+ egy kiegészítő, jobban strukturált specifikáció személyazonosságok tárolására (openspecs alapú)

A Namecoin kliens nagyon hasonlít a Bitcoin Core kliensre, lévén, hogy ugyanabból a forráskódból származik. Az installálásnál a kliens a namecoin blokkláncnak egy teljes másolatát letölti, és ezek után készen áll a nevek lekérdezésére és regisztrációjára. Három fő parancsa van:

* +name_new+: lekérdez vagy pre-regisztrál egy nevet
* +name_firstupdate+: regisztrál egy nevet, majd a regisztrációt nyilvánossá teszi
* +name_update+: megváltoztatja az adatokat, vagy frissít egy névregisztrációt

Például, a +mastering-bitcoin.bit+ domain-név regisztrálásához a +name_new+ parancs a következőképpen használható: 

----
$ namecoind name_new d/mastering-bitcoin
[
    "21cbab5b1241c6d1a6ad70a2416b3124eb883ac38e423e5ff591d1968eb6664a",
    "a05555e0fc56c023"
]
----

A +name_new+ parancs egy név-igényt regisztrál, azáltal, hogy létrehozza a névnek egy random kulccsal ellátott hash-ét. A +name_new+ által visszaküldött két karakterlánc a hash és a random kulcs (+a05555e0fc56c023+ a fenti példában), amelynek a felhasználásával a név regisztráció nyilvánossá tehető. Miután az adott igény regisztrációra került a namecoin blokkláncában, nyilvános regisztrációvá is konvertálható a +name_firstupdate+ paranccsal, a random kulcs megadásával:  

----
$ namecoind name_firstupdate d/mastering-bitcoin a05555e0fc56c023 "{"map": {"www": {"ip":"1.2.3.4"}}}}"
b7a2e59c0a26e5e2664948946ebeca1260985c2f616ba579e6bc7f35ec234b01
----

A fenti példa +www.mastering-bitcoin.bit+ domain-nevet az 1.2.3.4. IP címhez rendeli hozzá. A visszaküldött hash a a tranzakció id-je, amellyel a regisztráció nyomon követhető. A regisztrált neveket a +name_list+ parancs futtatásával nézheti meg:  

----
$ namecoind name_list
----
====
[source,json]
----
[
    {
        "name" : "d/mastering-bitcoin",
        "value" : "{map: {www: {ip:1.2.3.4}}}}",
        "address" : "NCccBXrRUahAGrisBA1BLPWQfSrups8Geh",
        "expires_in" : 35929
    }
]
----
====

A Namecoin regisztrációkat minden 36000 blokk után (kb. 200-250 naponként) frissíteni kell. A +name_update+ parancsnak nincs díja, így a Namecoin domainok megújítása ingyenes. Szerény díj ellenében egy webes interfészen keresztül egy megbízott fél is kezelheti a regisztrációt, valamint az automatikus frissítést és megújítást. Ha egymegbízott fél végzi a műveleteket, akkor szükségtelen,  hogy a namecoin klienst mindenki saját maga futtassa, ugyanakkor így elvész a Namecoin által kínált, decentralizált névnyilvántartás feletti független felügyelet.

==== Bitmessage

A Bitmessage egy bitcoin alt-chain, amely egy decentralizált és biztonságos üzenőrendszert implementál, lényegében egy szerver-mentes titkosított email rendszert. A Bitmessage cím használatával a felhasználók üzeneteket írhatnak és küldhetnek egymásnak. Az üzenetküldés folyamata nagyjából megegyezik a bitcoin tranzakciók működésével, azonban az üzenetek efemer jelenségek, 2 napnál tovább nem léteznek, így ha ennyi idő alatt nem kapja meg őket a címzett, akkor örökre elvesznek. A küldő és a fogadó álnevet használ, a jóváhagyott és hiteles bitmessage címükön kívül semmilyen más azonosítójuk nincs, de az erős hitelesítés miatt mindez azt is jelenti, hogy az üzenetek hamisítása nem lehetséges. A Bitmessage üzenetek dekódolására kizárólag a fogadó képes, így a bitmessage hálózata ellenáll a holisztikus felderítésnek: ahhoz, hogy egy üzenetet elcsípjenek, arra lenne szükség, hogy a lehallgató kompromittálja a fogadó készülékét.

==== Ethereum

Az Ethereum egy blokklánc-nyilvántartáson alapuló, Turing-teljes szerződés feldolgozó és végrehajtó platform. Ez nem egy bitcoin klón, hanem egy teljesen független elvi alapokon álló implementáció. Az Ethereumnak van saját fizetőeszköze, az úgynevezett _éter_ (_ether_), amely a szerződések végrehajtásához szükséges. A _szerződéseket_ az Ethereum blokklánca rögzíti. A szerződések alacsony színtű, byte-kód szerű, Turing-teljes nyelven vannak ábrázolva.  A szerződés lényegében egy olyan program, amely minden csomóponton az Ethereum rendszerében fut. Az Ethereum szerződések tárolhatnak adatokat, küldhetnek és fogadhatnak ether kifizetéseket, tárolhatnak ether-eket, illetve végtelen számú (innen a Turing-teljesség) kiszámítható műveleteket végezhetnek, és decentralizált autonóm szerver ügynökként funkcionálhatnak.

Az Ethereum viszonylag komplex rendszerek implementációjára is alkalmas, akár olyanokéra is, amelyek önmaguk is alt-chain implementációk. Például, alább egy Namecoinhoz hasonló név-regisztrációs szerződést láthatunk Ethereum-ban megírva (pontosabban, egy olyan magas szintű nyelven, amely lefordítható Ethereum kódra):

----
if !contract.storage[msg.data[0]]: # Már foglalt a kulcs?
    # Nem: akkor foglald le!
    contract.storage[msg.data[0]] = msg.data[1]
    return(1)
else:

    return(0) // Különben ne csinálj semmit
----

=== A fizetőeszközök jövője

Összességében, a digitális fizetőeszközök jövője még a bitcoinénál is fényesebb. A bitcoin egy teljesen új formájú decentralizált szervezetet és közmegegyezést vezetett be, ami egyben hihetetlen innovációk százainak is teret nyitott. Ezek az innovációk minden bizonnyal hatással lesznek a gazdaság számos szektorára, az elosztott rendszerektől a pénzügyön, a közgazdaságon, a fizetőeszközökön, és a központi bankokon keresztül egészen az államháztartásig és a kormányzati testületekig. Mostantól számos olyan emberi tevékenység válhat decentralizálttá, amelyhez korábban a hiteles és megbízható működés  érdekében egy központosított intézmény vagy szervezet jelenlétére volt szükség. A blokklánc és a közmegegyezés  innovációja jelentősen csökkenteni fogja a nagy  rendszerek létrehozásának és koordinációjának a költségét, egyben elkerüli a hatalomkoncentráció, a korrupció és a túlszabályozás csapdáját.  
