[[ch10]]
== A bitcoin biztonsági kérdései

A bitcoin biztonságos kezelése azért nehéz, mert a bitcoin nem olyan, mint egy bankszámla, vagyis nem egy elvont hivatkozást jelent valamilyen értékre. A bitcoin inkább a digitális pénzhez vagy az aranyhoz hasonlít. Bizonyára hallották már azt a mondást, hogy "A tulajdon a törvény kilenc tizede". Nos, a bitcoin esetén a tulajdon a törvény tíz tizedét jelenti. A bitcoinok zárolásának megszüntetéséhez szükséges kulcsok birtoklása egyenértékű azzal, mint ha készpénzünk vagy egy darab nemesfémünk lenne. Ha elveszítjük vagy elhagyjuk a kulcsot, vagy ellopják tőlünk, ill. ha véletlenül rossz összeget küldünk valakinek, akkor nincs semmilyen mentségünk, pont úgy járunk, mint ha egy forgalmas járdára készpénzt szórnánk.

A bitcoinnak viszont vannak olyan lehetőségei, amellyel az arany vagy a bankszámlák nem rendelkeznek. A bitcoin kulcsokat tároló pénztárcáról a többi állományhoz hasonlóan biztonsági másolatot lehet készíteni. A másolat több példányban tárolható, vagy akár papírra is kinyomtatható, ha fizikai biztonsági másolatra van szükség. A készpénzről, az aranyról vagy a bankszámlákról nem lehet "biztonsági másolatot" készíteni. A bitcoin annyira különbözik minden más őt megelőző dologtól, hogy a bitcoin biztonsági kérdései is újfajta megközelítést tesznek szükségessé. 


=== Biztonsági alapelvek

A bitcoin legfontosabb sajátossága a decentralizáció, ennek pedig fontos biztonsági következményei vannak. Egy centralizált modell, pl. egy hagyományos banki hálózat a hozzáférési jogosultságoktól és ezek vizsgáltatától reméli a rossz fiúk rendszertől történő távol tartását. Ezzel szemben egy decentralizált rendszer a felelősséget és a rendelkezési jogot a végfelhasználó kezébe adja. Mivel a hálózat biztonsága nem a hozzáférési jogokon, hanem a munkabizonyítékokon alapul, a hálózat nyílt lehet, és a bitcoin forgalmához nincs szükség titkosításra.

Egy hagyományos kifizető hálózatban, pl. egy hitelkártya rendszerben a "fizetség" valójában nyitott, mivel tartalmazza a felhasználó privát azonosítóját (a hitelkártya számot). A kezdeti levonás után ezen azonosító birtokában bárki képes a pénz újbóli "lehívására", és a tulajdonostól történő ismételt levonására. Emiatt a kifizető hálózatot a végpontok között titkosítással kell biztonságossá tenni, és biztosítani kell, hogy a forgalmat semmilyen lehallgatás vagy közbenső személy se zavarhassa meg, sem menet közben, sem a tárolás során. Ha egy rossz fiú jut be a rendszerbe, akkkor képes lesz arra, hogy kompromittálja az aktuális tranzakciót, _és_ új tranzakciókat hozzon létre. De ami még ennél is rosszabb, a felhasználó adatai is kompromittálódnak, a személyazonosságának az ellopása fenyegeti, és lépéseket kell tennie, hogy megakadályozza a kompromittálódott számlák jogtalan használatát.

A bitcoin teljesen különbözik ettől. Egy bitcoin tranzakcióval csak egy adott érték továbbítható egy adott fogadó félnek, a tranzackiót pedig nem lehet meghamisítani vagy módosítani. Semmilyen privát adatot sem lehet megtudni belőle, például a tranzakcióban részt vevő felek személyazonosságát, és nem lehet vele további kifizetéseket eszközölni. Ezért a bitcoin hálózatban nincs szükség titkosításra vagy a lehallgatás elleni védelemre. A bitcoin tranzakciók publikus csatornákon, pl. nem biztonságos Wifi vagy Bluetooth csatornákon is továbbíthatók anélkül, hogy ez bármilyen negatív hatással lenne a biztonságra.

A bitcoin decentralizált biztonsági modellje a végfelhasználók kezébe sok hatalmat ad. De a hatalommal felelősség is jár: a kulcsok titkosságának biztosítása. A legtöbb felhasználó számára ez nem egyszerű dolog, különösen ha olyan általános célú számítástechnikai eszközökről van szó, mint az Internethez kapcsolódó okostelefonok vagy notebook-ok. A bitcoin decentralizált modellje megakadályozza ugyan a hitelkártyák esetében tapasztalt tömeges kompromittálódást, de sok végfelhasználó képtelen a kulcsok megfelelő védelmére, és a hackerek egyesével levadásszák őket.


==== A bitcoin rendszerek biztonságos fejlesztése

A bitcoin rendszerek fejlesztői számára a decetralizáció a legfontosabb alapelv. A legtöbb fejlesztő már találkozott a centralizált biztonsági modellekkel, és emiatt hajlamos arra, hogy az ilyen modelleket alkalmazza a bitcoin fejlesztései során is, ez pedig katasztrofális következményekkel jár.

A bitcoin biztonsága a kulcsok fölötti decentralizált rendelkezési joggal és a bányászok által végzett független tranzakció ellenőrzésen alapul. Ha szeretnénk kihasználni a bitcoin nyújtotta biztonságot, akkor biztosítanunk kell a bitcoin biztonsági modellnek megfelelő működést. Egyszerűen szólva: a fejlesztő ne vegye el a felhasználó kulcsok feleltti rendelkezési jogát, és a tranzakciókat ne vigye a blokkláncon kívülre.

Például sok korai bitcoin váltóban a felhasználók pénzét egyetlen egy "meleg"/"éles" pénztárcában gyűjtötték össze, melynek kulcsait egyetlen egy szerveren tárolták. Az ilyen felépítés megfosztotta a felhasználókat a felügyeleti joguktól, és a kulcsok fölötti felügyeleti jogot egyetlen rendszerbe koncentrálta. Sok ilyen rendszert feltörtek, ami rendkívül hátrányos következményekkel járt ezen rendszerek felhasználói számára.

Egy másik szokásos hiba a tranzakciók "blokkláncon kívüli" kezelése, azzal a hibás szándékkal, hogy csökkentsék a tranzakciós díjakat és felgyorsítsák a tranzakciók feldolgozását. Egy ilyen "blokkláncon kívüli" rendszer a tranzakciókat egy belső, központosított főkönyvben tárolja, és  csak időnként szinkronizálja őket a bitcoin blokkláncával. Ez a gyakorlat ismét csak a bitcoin decentralizált biztonságát helyettesíti egy saját, centralizált módszerrel. Ha a tranzakciók a blokkláncon kívül vannak, akkor a nem eléggé biztonságos centralizált főkönyvek meghamisíthatóak, és a pénzeszközök észrevétlenül elszivárogtathatóak.

Jól gondolja meg, hogy kiemeli-e a pénzeszközök kezelését a bitcoin decentralizált biztonsági környezetéből. Ha így döntene, akkor készüljön fel arra, hogy a működés biztonságát költséges beruházásokkal, számos hozzáférési réteggel és könyvvizsgálókkal kell megteremtenie (ahogyan ezt a hagyományos bankok teszik). Még ha van is pénze és tudása egy ilyen robusztus biztonsági modell megteremtésére, az ilyen felépítés csupán a hagynományos pénzügyi hálózatok törékeny modelljét utánozza, melyben súlyos problémát jelent a személyazonosság ellopása, a korrupció és a hűtlen kezelés. Ha szeretné a bitcoin decentralizált modelljének előnyeit élvezni, akkor el kell kerülnie azt a kísértést, melyet a centralizált architektúrák/modellek jelentenek. Lehet, hogy ezek közismertebbek, de végső soron a bitcoin bizonságát sodorják veszélybe.


==== A bizalom alapja

A hagyományos biztonsági rendszerek egy olyan fogalmon alapulnak, melynek neve _a bizalom alapja_. Ez nem más, mint egy biztonságos mag, mely az egész rendszer vagy alkalmazás biztonságának az alapját alkotja. A biztonsági megoldások e köré épülnek koncentrikus körök formájában, a hagymahéjakhoz hasonlóan, és a biztonságot a kiindulóponttól kifelé terjesztik ki. Minden egyes réteg a megbízhatóbb belső rétegre épül, és hozzáférési jogokat, digitális aláírásokat, titkosítást és más biztonsági alapelemeket használ. Ahogy a szoftver rendszerek egyre bonyolultabbakká válnak, egyre valószínűbb, hogy hibákat tartalmaznak, ami biztonsági szempontból kiszolgáltatottá teszi őket. Emiatt minél bonyolultabb egy szoftver rendszer, annál nehezebb a biztonságát garantálni. A bizalom alapja révén biztosítható, hogy leginkább a rendszer legkevésbé bonyolult, és emiatt legkevésbé támadható részében bízzunk, és a bonyolultabb szoftvert e köré építsük. Ez a biztonsági architektúra különféle szinteken ismétlődik, és a bizalom alapját először egyetlen egy rendszer hardverén belül teremti meg, majd a bizalomnak ezt az alapját terjeszti ki az operációs rendszeren keresztül a magasabb szintű rendszer-szolgáltatásokra, és végül a számos szerverre, melyek a csökkenő bizalom koncentrikus köreit alkotják.

A bitcoin biztonsági architektúrája nem ilyen. A bitcoin esetében a konszenzus-rendszer teremti meg a biztonságos főkönyvet, amely teljesen decentralizált. A blokkláncban a genezis blokk a bizalom alapja, és az ellenőrzések révén jön létre a bizalmi lánc egészen az aktuális blokkig. A bitcoin rendszerekben a blokklánc használható, és a blokkláncot kell használni a bizalom alapjaként. Ha ön bonyolult bitcoin alkalmazásokat tervez, melyek sok különböző rendszeren futó szolgáltatásból épülnek föl, akkor gondosan meg kell vizsgálnia, hogy a biztonsági rendszeren belül hol van a rendszer biztonságának az alapja. Végső soron csak egyetlen dologban szabad explicit módon megbíznia: a teljesen ellenőrzött blokkláncban. Ha az ön alkalmazása explicit vagy implicit módon a blokkláncon kívül bármi másban megbízik, az problémák forrását jelentheti, mivel támadható pontokat teremt a rendszeren belül. Az alkalmazás biztonságának vizsgálatára jó módszert jelent minden egyes összetevő külön történő vizsgálata, és annak a képzelt esetnek a kiértékelése, hogy mi történik, ha a vizsgált összetevő teljesen kompromittálódik, és a rossz fiúk fennhatósága alá kerül. Ennek megfelelően tekintse át az alkalmazás elemeit sorban egymás után, és vizsgálja meg, hogy milyen hatással lenne a biztonságra, ha az illető összetevő kompromittálódna. Ha az összetevők kompromittálódását követően az alkalmazás már nem biztonságos, akkor ez azt mutatja, hogy ön implicit módon bizalmat vetett ezekbe az elemekbe. Egy nem sérülékeny bitcoin alkalmazás csak a bitcoin konszenzus-mechanizmus kompromittálódása révén támadható. Ez azt jelenti, hogy a bizalom alapját a bitcoin biztonsági architektúra legerősebb része jelenti.

A bitcoin váltók bukásai számos példát szolgáltattak ennek hangsúlyozására, mert a biztonsági architektúrájuk és felépítésük még a legfelületesebb vizsgálat során is megbukott. A váltók centralizált megvalósítása során a blokkláncon kívül számos más építőelembe helyeztek explicit bizalmat, például a pénztárcákba, a centralizált főkönyvi adatbázisokba, a támadható titkosító kulcsokba stb. Fokozta a bajt, hogy a legtöbb esetben ezek a megbízhatónak hitt elemek még a legkezdetlegesebb biztonsági eszközökkel sem rendelkeztek.


=== A felhasználók számára követendő példák

Az emberek évezredek óta használnak fizikai biztonsági eszközöket. Ezzel szemben a digitális biztonságra vonatkozó tapasztalatok kevesebb mint 50 évesek. A modern álalános célú operációs rendszerek nem nagyon biztonságosak, és nem nagyon alkalmasak digitális pénz tárolására. Számítógépeinket állandóan külső támadásoknak tesszük ki az állandó Internet összeköttetések révén. Szoftver komponensek ezreit futtatjuk, melyek több száz különböző szerzőtől származnak, és gyakran korlátozás nélkül elérik a felhasználó adatállományait. Elég egyetlen egy rossz szándékú szoftver a több ezer között ahhoz, hogy kompromittálja a billentyűzetet és az adatállományokat, és ellopja a pénztárca alkalmazásokból az ott tárolt bitcoinokat. Az, hogy a számítógép virusmentes és trójai-mentes állapotban legyen, a legtöbb felhasználó üzemeltetési tudását meghaladó feladat, a felhasználók egy elenyésző töredékét kivéve. 

Az információ-biztonság évtizedes kutatása és eredményei ellenére a digitális javak még mindig nagyon sérülékenyek egy céltudatos ellenféllel szemben. Még a pénzügyi szolgáltatók, hírszerző szervezetek és hadiipari szállítók legjobban védett és legkorlátozottabban használható rendszereit is gyakran feltörik. A bitcoin olyan digitális javakat teremtett, amelynek belső értéke van, ellopható, azonnal és visszavonhatatlanul az új felhasználókhoz irányítható át. Ez a hackerek számára nagyon nagy motivációt jelent. Eddig a hackereknek a személyazonosságot vagy a számla adatokat (pl. hitelkártya számokat, bankszámla adatokat) más értékre kellett konvertálniuk, ha sikerült kompromittálniuk őket. A pénzügyi adatok korlátozása és a pénzmosás korlátozása ellenére egyre nagyobb lopásokat láthattunk. A bitcoin elmélyíti ezt a problémát, mivel nincs szükség a pénzmosásra - a bitcoin egy digitális jószág, melynek belső értéke van.

Szerencsére a bitcoin a számítógépes biztonság javítását is elősegíti. A bitcoint megelőzően a számítógép kompromittálódásának a veszélye közvetett és bizonytalan volt, a bitcoin viszont ezt a veszélyt nyilvánvalóvá és világossá tette. A bitcoin számítógépen történő tárolása ráirányította a figyelmet arra, hogy fokozott biztonságra van szükség. A bitcoin és más digitális pénzek elterjedésének közvetlen következményeként mind a hackelési módszerek, mind a biztonsági megoldások terén eszkalálódott a helyzet. Egyszerű szavavakkal, a hackerek számára a bitcoin nagyon csábító célt jelent, a felhasználók pedig minden módon szeretnék megvédeni magukat.

Az utóbbi három évben a bitcoin elterjedésének közvetlen következményeképpen hatalmas innováció zajlott le az információbiztonság területén, a harveres titkosítás, a hardveres kulcstárolás és harveres pénztárcák, a többszörös aláírás valamint a digitális letét formájában. A következő részekben a gyakorlati biztonság legjobb, legkövetendőbb példáit vizsgáljuk meg.


==== Fizikai bitcoin tárolás

Mivel a felhasználók többsége számára a fizikai biztonság sokkal megfoghatóbb az információbiztonságnál, a bitcoinok védelmére egy nagyon hatékony módszert jelent, ha fizikai alakra konvertáljuk őket.  A bitcoin kulcsok nem mások, mint hosszú számok. Ez azt jelenti, hogy fizikai alakban tárolhatók, például kinyomtathatók vagy rávéshetők egy érmére. A kulcsok védelme ekkor egyszerűen a kinyomtatott bitcoin kulcsok fizikai védelmét jelenti. A papírra kinyomtatott bitcoin kulcsokat "papír pénztárcának" hívják. Sok szabadon használható eszköz van, mellyel papír tárcák hozhatók létre. Személy szerint én a bitcoinjaim túlnyomó többségét (99%-ánál is többet) papír pénztárcákban tárolom, BIP0038 szerinti titkosítással, több példányban kinyomtatva, és páncélszekrényekbe elzárva. A bitcoinok offline módon történő _hideg tárolása_ az egyik leghatékonyabb védelmi módszert jelenti. Hideg tároláskor a kulcsokat egy offline rendszeren generálják (vagyis egy olyan rendszeren, amely soha sem volt az Internetre kapcsolva), a kulcsokat pedig offline módon, papíron, vagy más digitális tároló eszközön, pl. USB kulcson tárolják.


==== Hardveres pénztárcák

Hosszabb távon a bitcoinok biztonságát egyre inkább a külső módosításokkal szemben védett hardveres pénztárcák fogják megteremteni. Az okostelefonokkal vagy az asztali számítógépekkel ellentétben az ilyen célra épített hardveres pénztárcáknak csak egy célja és feladata van - a bitcoinok biztonságos tárolása. Mivel nincs bennük általános célú szoftver, amely kompromittálható, és az interfészeik a célnak megfelelően korlátozottak, ezért a hardveres pénztárcákkal a laikus felhasználók szinte korlátlan biztonsághoz juthatnak. Azt várom, hogy a jövőben túlnyomó részben hardveres pénztárcákat fognak használni a bitcoinok tárolására. Egy ilyen hardveres pénztárca például a Trezor (http://www.bitcointrezor.com/).


==== Kockázat kezelés (a kulcsok elvesztése vagy ellopása)

Míg a legtöbb felhasználó jogosan a lopás miatt aggódik, van egy még nagyobb veszély: a kulcsok elvesztése. Adatállományok bármikor elveszhetnek, de ha bitcoin tárolására használták őket, akkor a veszteség még fájdalmasabb. Miközben szeretnénk biztonságban tudni a bitcoin pénztárcáinkat, vigyáznunk kell arra, hogy ne menjünk túl messzire, mert emiatt is elveszíthetjük a bitcoinjainkat. 2010 nyarán egy jól ismert bitcoin szervezet majdnem 7000 bitcoint vesztett el ily módon. A lopás elleni védekezés gyanánt titkosított biztonsági másolatok bonyolult rendszerét használták. Végül véletlenül elveszítették a titkosító kulcsokat, emiatt a biztosági másolatok nem értek semmit, és egy vagyont veszítettek. Olyan ez, mint ha pénzt ásnánk el a sivatagban: ha túl jól sikerül a dolog, akkor nem biztos, hogy megtaláljuk az elásott kincset. 


==== Kockázat megosztás

Vajon önök az egész vagyonukat készpénzben tartják a pénztárcájukban? A legtöbben ezt meggondolatlanságnak tartanák, ugyanakkor a bitcoin felhasználók gyakran az összes bitcoinjukat egyetlen pénztárcában tartják. A felhasználóknak inkább több különböző bitcoin pénztárca között kellene szétosztani a kockázatot. Egy óvatos felhasználó csak a bitcoinjainak egy kis részét, mondjuk kevesebb mint 5%-át tartja "zsebpénzként" az online vagy mobil pénztárcájában. A többit különféle egyéb tárolási módszerekkel pl. az asztali számítógépén lévő és az offline pénztárcák (hideg tároló) között kellene szétosztania.


==== Többszörös aláírás és vezetés/irányítás

Ha egy cég vagy egy személy nagy mennyiségű bitcoint tárol, akkor érdemes megfontolnia a több aláírással rendelkező (multi-signature) bitcoin címek használatát. A több aláírással rendelkező címek úgy biztosítják a pénzösszegek biztonságát, hogy a kifizetéshez egynél több aláírásra van szükség. Az aláíró kulcsokat különböző helyeken kell tárolni, és különböző emberek fennhatósága alá kell helyezni. Vállalati környezetben például a kulcsokat egymástól függetlenül kell előállítani, és az igazgatósági tagok között kell szétosztani oly módon, hogy önmagában egyetlen személy ne tudjon hozzájutni a pénzösszegekhez. A többszörös aláírással rendelkező címekkel redundancia is megvalósítható. Ebben az esetben egyetlen személynek van több kulcsa, és a kulcsok különböző helyeken vannak tárolva.


==== Túlélési képesség

Az egyik gyakran elhanyagolt biztonsági szempont a bitcoinok rendelkezésre állása, különösen a kulcs tulajdonosának cselekvésképtelensége vagy halála esetén. A bitcoin felhasználóknak adott egyik tanács az, hogy használjanak bonyolult jelszavakat, és tartsák a kulcsaikat biztonságban és titokban, valamint hogy a kulcsokra vonatkozó információkat senkivel se osszák meg. Sajnos, az ilyen gyakorlat szinte teljesen kizárja, hogy a felhasználó családja bármilyen pénzhez jusson, ha az eredeti felhasználó nem képes megszüntetni a pénz zárolását. Mi több, a legtöbb esetben a bitcoin felhasználók családja nem is tud a bitcoinban tartott tőkéről.

Ha önnek sok bitcoinja van, akkor fontolja meg, hogy a hozzáférés részleteit nem kellene-e megosztania egy bizalmas rokonnal vagy egy jogásszal. Bonyolultabb túlélési módszert lehet létrehozni többszörös aláírással vagy egy "digitális örökség" kezelésére szakosodott jogász segítségét igénybe véve.


=== Befejezés

A bitcoin egy teljesen új, eddig példa nélkül álló és bonyolult technológia. Idővel jobb biztonsági eszközök és megoldások kifejlesztése várható, melyeket a laikusok is könnyebben tudnak majd használni. Jelen pillanatban a bitcoin felhasználók a fenti tanácsok alkalmazásával tudnak  biztonságos és gondtalan bitcoin használatot teremteni maguknak.

